namespace ChinookDatabase.DdlStrategies
{
    public class EffiProzStrategy : AbstractDdlStrategy
    {
        public EffiProzStrategy()
        {
            CanReCreateDatabase = true;
        }

        public override string Name
        {
            get { return "EffiProz"; }
        }

        public override string Identity
        {
            get { return "GENERATED BY DEFAULT AS IDENTITY(INCREMENT BY 1 START WITH 1)"; }
        }

        public override bool CreatePrimaryKeyOnTableCreate
        {
            get { return false; }
        }

        public override string FormatName(string name)
        {
            return string.Format("\"{0}\"", name);
        }

        public override string WriteCreateDatabase(string databaseName)
        {
            return string.Format("CREATE SCHEMA {0} AUTHORIZATION DBA;", FormatName("dbo"));
        }
    }
}